# Generated by Django 3.1.5 on 2021-02-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentryform',
            name='batch_number',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='purchaseentryform',
            name='brand_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
