# Generated by Django 3.1.5 on 2021-02-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210224_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturnentryform',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseentryform'),
        ),
    ]
