# Generated by Django 3.1.5 on 2021-02-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210224_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
