# Generated by Django 3.1.5 on 2021-02-24 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210224_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('remarks', models.CharField(max_length=1000, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseentryform')),
            ],
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='stock',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseentryform'),
        ),
        migrations.DeleteModel(
            name='LostDamage',
        ),
    ]
