# Generated by Django 3.1.5 on 2021-02-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210224_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseentryform',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='date',
            field=models.DateField(),
        ),
    ]
