# Generated by Django 3.1.5 on 2021-03-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210225_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='rack_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.rack'),
        ),
    ]
